### ISSUE TITLE
Assetto Corsa missing lap 1 position data

### ISSUE THREAD

**Issue by mhightree** [mauserrifle/simresults#42]
I have an instance where lap 1 is missing for all participants.   All other laps are processed ok.   This is an Assetto Corsa json file.   I can see lap 1 in the file for all participants.  Any workaround for this problem?    Thanks.

**Comment by mauserrifle** [comment]
Could you share the log files? Then I can just fix it. Thanks!

**Comment by mhightree** [comment]
I have attached two race result files.   Both exhibit the issue.   Thanks for looking at the issue!
[AssettoCorsaRaceResultFiles.zip](https://github.com/mauserrifle/simresults/files/924279/AssettoCorsaRaceResultFiles.zip)

**Comment by mauserrifle** [comment]
Thnx. I can see the first lap in the json on the web result. I don't see any issue?

http://simresults.net/170416-0vh
http://simresults.net/170416-jX2

**Comment by mhightree** [comment]
That is interesting.   When I process those files I don't get lap one.   Here are my results.   I don't have this problem processing rF1, rF2 or Automobilista files.   Ok, well thank you for checking.   I will recheck my code.

[http://www.simracingonline.co.uk/racing/event.44/racereport/2](url)
[http://www.simracingonline.co.uk/racing/event.45/racereport/83](url)

**Comment by mauserrifle** [comment]
Ok. Keep me posted if its an issue in the library.

**Comment by mhightree** [comment]
Hello,
I think I figured out what is happening.    The Lap 1 data does exist in AC.    There are two problems.   First my code was not defensive enough against NULL values.    Second issue is that **$lap->getPosition()** returns NULL for lap 1 in AC files.     Some evidence of that is from your simresults web site.   I compared an AC result file with an rF2 file.    See attached image.    You will notice that the AC file shows lap 2 as the first lap position while the rF2 shows the Grid position and Lap 1 position.   I was trying to store the lap 1 position, which doesn't exist, and getting runtime in my code.    

Let me know if you have any questions.   

![ac_result_file](https://cloud.githubusercontent.com/assets/26889041/26523403/6cf09b54-42dc-11e7-9856-c9562d0a8997.png)

**Comment by mauserrifle** [comment]
Could you send me that specific log?

**Comment by mauserrifle** [comment]
Never mind. I got it with my logs too. The weird thing is. L1 is missing from the exact same log the integration tests are made off. And in the tests lap 1 position is validated. Weird!

**Comment by mauserrifle** [comment]
Found the issue:
https://github.com/mauserrifle/simresults/blob/develop/lib/Simresults/Data/Reader.php#L340

Positions are only fixed from lap 2 and on because some sims did have grid position. But in AC case that info is not in the server json files. So need to make it variable per reader. Will fix it soon.

Thnx for the detailed info!

**Comment by mauserrifle** [comment]
Actually this aint a bug. In AC there is no position data at all. The parser fixes this by reading out the laps of all participants. But the position is for the beginning of the lap. We can't decide the de position for lap 1. Because there are no times to compare yet before that.
