### ISSUE TITLE
Qualification times are missing in Raceroom

### ISSUE THREAD

**Issue by rdemeyer** [mauserrifle/simresults#45]
Hi,

Since a few weeks, the qualifications times are missing in the display of raceroom qualification table, like here : http://simresults.net/171023-vG1

Those times are still in the Json so it should be a bug : 

Ex : 

```
{
"FullName":"David Torned",
"Username":"Torned",
"Car":"McLaren MP4-12C GT3",
"CarPerformanceIndex":60,
"Position":2,
"PositionInClass":2,
"BestLapTime":97958,
"TotalTime":-1,
"FinishStatus":"Finished",
"RaceSessionLaps":[
{
"Time":-1000,
"Position":2,
"PitStopOccured":false
}
]
```

I've looked in the code and I think I know why it does not worked. Qualification has a section "RaceSessionLaps" (which is wierd) and has a consequence, you parser does not take into account "BestLapTime" which is where we can find the time for the qualification. See line 183 and 212 of Data/Reader/RaceRoomServer.php.

Thanks

**Comment by mauserrifle** [comment]
This issue has been fixed. Thanks for reporting!

**Comment by rdemeyer** [comment]
Quick reaction, impressive! Thanks, (I've seen after there was another pull request for that)

**Comment by mauserrifle** [comment]
Correct. Work was already done 👍
