### ISSUE TITLE
Integration test R3E pitstops count

### ISSUE THREAD

**Issue by mauserrifle** [mauserrifle/simresults#46]
Create test for: https://github.com/mauserrifle/simresults/pull/44

**Comment by hieblmedia** [comment]
Here a testfile with pitstops:
[log-with.pitstops.json.zip](https://github.com/mauserrifle/simresults/files/1443148/log-with.pitstops.json.zip)

**Comment by mauserrifle** [comment]
I reverted the pull request. Better solution:
https://github.com/mauserrifle/simresults/commit/101855149665d4a5bc55da3c09253877e9af049e
