### ISSUE TITLE
Integration test [R3E] Fix empty qualify times

### ISSUE THREAD

**Issue by mauserrifle** [mauserrifle/simresults#47]
Integration test for: https://github.com/mauserrifle/simresults/pull/43

**Comment by mauserrifle** [comment]
Log possible useful:
[log.with.bestlaptime.json.tar.gz](https://github.com/mauserrifle/simresults/files/1430969/log.with.bestlaptime.json.tar.gz)

**Comment by hieblmedia** [comment]
Here another testfile.
[BestLapTime-1000.zip](https://github.com/mauserrifle/simresults/files/1443143/BestLapTime-1000.zip)
