### ISSUE TITLE
ProjectCars 2 no result data for admin/first player on ded 

### ISSUE THREAD

**Issue by krobonix** [mauserrifle/simresults#54]
Hi , I'm one of the admins at simracingonline.co.uk  & we have an issue with my info (as admin & first on the server) never appearing in the results for pc2 , I have done the edits to the sms_stats_json ,here are my edits >

**-- Session game state changes.
function handle_session_game_state_change( old_state, new_state )
	if not old_state or old_state == "" then
		old_state = "None"
	end
	session_game_state = new_state
	if ( old_state == "None" ) and ( new_state == "Lobby" ) then
		handle_new_session_lobby()
	elseif ( old_state == "Returning" ) and ( new_state == "Lobby" ) then
		handle_returning_session_lobby()
	elseif ( old_state == "Lobby" ) and ( new_state == "Loading" ) then
		handle_session_loading()
	elseif ( old_state == "Loading" ) and ( new_state == "PostRace" or new_state == "Race" ) then
		handle_session_loaded()
	elseif ( old_state == "PostRace" or old_state == "Race" ) and ( new_state ~= "PostRace"  and new_state ~= "Race" ) then
		if new_state == "None" then
			handle_session_finished_prematurely()
		else
			handle_session_finished()
		end
	end
end**

These seem to work as we now have results ! however my info is never parsed and Im left out of every result ? 
here is a pic of race 1 (of 2 that day & should be the last 2 races in the results) Im admin on the server and finished 6th 'Rob Milliken'

![send to mouser](https://user-images.githubusercontent.com/35407884/34910007-8eaf2eaa-f861-11e7-8c7e-6070420e7a14.jpg)
 
& this
This is what we get from simresults without any of my  info ..

![yyyyxxxx](https://user-images.githubusercontent.com/35407884/34910034-197afd34-f862-11e7-9967-98c99d8e5ad4.jpg)

We don't know what to do ?? its been like this from the start meaning my data is never shown ..

 I tried to upload my sms_stats_data but i dont have winzip and wrar wont work ..it's posted in this thread at SMS forums  http://forum.projectcarsgame.com/showthread.php?56405-No-Race-Results-in-sms_stats_data-json&p=1461236&viewfull=1#post1461236

Im reading in the forum that other players have it working with no issues & so it must be something on my end ? 
Thanks in advance if you find any time to help ! 
Rob .. ;-)

**Comment by krobonix** [comment]
I do see my info in the sms_stats_data but its not getting parsed ? 
 "last_joined" : 1515781290,
        "name" : "Rob Milliken"
      },
      "76561198023215801" : {
        "counts" : {
          "qualify" : {
            "positions" : {},
            "positions_per_size" : {},
            "states" : {}
          },
          "race" : {
            "positions" : {
              "4" : 1,
              "5" : 1
            },
            "positions_per_size" : {
              "0" : {
                "4" : 1,
                "5" : 1
              }
            },
            "states" : {
              "finished" : 2
            }
          },
          "race_finishes" : 0,
          "race_joins" : 6,
          "race_loads" : 6,
          "race_loads_done" : 6,
          "track_distances" : {
            "-52972612" : 417211,
            "521933422" : 143340
          },
          "tracks" : {},
          "vehicle_distances" : {
            "1626504761" : 560551
          },
          "vehicles" : {}

**Comment by mauserrifle** [comment]
Hi krobonix,

Thanks for the detailed info! I fixed so you are now in the results. But note that you have no "events" in your data. So all results are 1 lap only (final result data). I cannot help fixing the events as I do not know and am just parsing. Please seek help with the other admins on the forum.

Cheers!

Maurice

**Comment by krobonix** [comment]
Thank You ! 
yes I saw that as well .. I must be somthing to do with being the in game admin on the server ?? the last 2 races were 20 min races ..16-or so laps ..and shows 0 for me ;-( any ideas?

**Comment by mauserrifle** [comment]
What do you mean last two races shows 0? I see 1 lap for all. I am looking at this result from your uploaded log files: http://simresults.net/180116-Q1S 

Please point me in the right direction.

**Comment by krobonix** [comment]
MY Bad I ment 0 data ( not laps .. But now after some tweaks to the lua_cnfg to events= true it seems to be working !!

**Comment by mauserrifle** [comment]
Ok great to hear!
