### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by dams16198** [mauserrifle/simresults#65]
I try to install the GitHub, but once the installation is finished nothing appears. error 404.
I must have missed something

**Comment by dams16198** [comment]
Sorry for the inconvenience.
I wanted to use your code to create a live timming.
the code works but in the example it only displays a few digits.
I know it takes a css to lay it out.
![IMG_20200714_120100](https://user-images.githubusercontent.com/4959212/87413199-47fc3c80-c5ca-11ea-8470-341d4dc642a4.jpg)

**Comment by mauserrifle** [comment]
Hi Dans,

Glad you figured it out. The example only shows the best lap gap as a demonstration. You will have to code the rest such as displaying the full results and style it. Make sure to carefully read the classes (such as `Session` and `Participant`) callable methods as a starting point.

**Comment by dams16198** [comment]
Thank you
