### ISSUE TITLE
Automobilista 2

### ISSUE THREAD

**Issue by dams16198** [mauserrifle/simresults#66]
Sorry again for the surely stupid questions.

when i try a sms_stast_data.json from ams2 it doesn't read anything.
however on the site he transforms it into pcars1

**Comment by mauserrifle** [comment]
Hi Dams,

No stupid questions :)

When you do the following:

```
$participants = $session->getParticipants();
print_r($participants);
```

there's really no data? That would be weird. The website runs the latest commit from develop branch.

If you can. Please send me example logs of Automobilista 2 to my email. I still need to create proper support for this game. Though I have not received any log files so far.

**Comment by dams16198** [comment]
I will send it to you quickly
there will only be 1 or 2 sms_stats_data.json files

**Comment by dams16198** [comment]
with "print_r"
![sms_stats_data](https://user-images.githubusercontent.com/4959212/87558922-f206c200-c6b9-11ea-86e2-06f2b4eb51d5.jpg)

**Comment by mauserrifle** [comment]
> I will send it to you quickly
> there will only be 1 or 2 sms_stats_data.json files

Thanks! This helped me alot in detecting Automobilista 2 for now with some vehicle id's I was able to find. But detecting the game with the first file is not possible, the vehicle id's are in Project Cars too, ugh.

It would be great if I can receive the attributes json file from the dedicated server API. It looks like this:
https://github.com/mauserrifle/simresults/blob/develop/lib/Simresults/Data/Reader/ProjectCars2Attributes.json

It's in some kind of API documentation for the server. I sometimes receive an updated version of PC1/2. It should be possible to fetch it for Automobilista 2 too so I can convert vehicle id's to names.

But if you don't know how to fetch it, no problem.


==



> with "print_r"
> ![sms_stats_data](https://user-images.githubusercontent.com/4959212/87558922-f206c200-c6b9-11ea-86e2-06f2b4eb51d5.jpg)


Your `print_r` confirms there's data. Are you sure you are also looping all sessions?

```
        $sessions = $reader->getSessions();

        foreach ($sessions as $session)
        {
             ........
        }

```

**Comment by mauserrifle** [comment]
Vehicle and track names are implemented. Big thanks for the help! Closing this issue.
