### ISSUE TITLE
About vehicle name of ACC result page

### ISSUE THREAD

**Issue by GravityMsc** [mauserrifle/simresults#67]
Well, this might be a small request. Could you use exact car name instead of 'car model xx'? There is an exist 'number-name' carmap in your code, I think it won't cost too much time.
![image](https://user-images.githubusercontent.com/17739114/87895455-10810a80-ca78-11ea-889e-f969f9529b0c.png)

**Comment by mauserrifle** [comment]
It's added :)

Cheers.
Maurice
