### ISSUE TITLE
API Behaviour

### ISSUE THREAD

**Issue by schmoomsm** [mauserrifle/simresults#69]
Hi!

First off, thanks for this great tool, website, and API, which I'm trying to implement on my site.

I have a working JSON, which you can review [here](http://battlegoatracing.com/bgr/ACC.json). A script populates the list of results files on each run. The page loads and displays the expected graphics, and the three race results I would expect--these appear as tabs labelled "Race 1", "Race 2", etc. You can see it [here](https://simresults.net/remote?results=http://battlegoatracing.com/bgr/ACC.json&version=2). 

My question is about the point/function of the drop-down menu. I would have expected to see Race 1, Race 2, etc. in that drop-down instead of in the tabs. 

If the individual results are supposed to be in the tabs, what is the drop-menu supposed to do?

Thx for your attention.

**Comment by mauserrifle** [comment]
Hi schmoomsm ,

Each dropdown option is a result with 1 or multiple logs. Thus you have total control over. For example you could make a results array with season 1, season 2 (in dropdown). And each season result can contain multiple logs (race 1, race 2 etc).

As you can see in the example on the API page:
https://simresults.net/remote?results=https://simresults.net/example.json

In your case you have multiple logs in 1 result array. If you wish to have multiple dropdowns containing just 1 race. Create multiple results array with 1 log only.

Not related but I see now that I should make the config also per result possible (optional). I will make this soon.

Hope it makes sense with the provided example.

Cheers,
Maurice

**Comment by schmoomsm** [comment]
Thanks for the response! I think I understand.

**Comment by schmoomsm** [comment]
Got it working!!! Thank you!

JSON: https://battlegoatracing.com/bgr/ACC.json and https://battlegoatracing.com/bgr/AC.json

Thanks again for this great tool!

**Comment by mauserrifle** [comment]
Great! Though the dropdown active selection seems to be not working fully here when I browse your results page. I think it's s bug on my part. I will look into it Tuesday I think.

**Comment by schmoomsm** [comment]
Thx!

My site is set-up to not cache json files per your direction and I have my links pointing to a static version number. When my jsons are recreated each day (game server and webserver sync results file once per day and generate a new json per game), will my links continue to show the newest content?

Link to ACC: https://simresults.net/remote?results=http://battlegoatracing.com/bgr/ACC.json&version=10
Link to AC: https://simresults.net/remote?results=http://battlegoatracing.com/bgr/AC.json&version=10

Thx.

**Comment by mauserrifle** [comment]
Ye if you increment the version number, simresults should ignore it's own cache and always fetch your updated json.

**Comment by schmoomsm** [comment]
what if my increment stays at 10? Will I always see dated results, or will it force a refetch each day?

**Comment by mauserrifle** [comment]
Cache is 24 hours. So it will eventually be refetching and up to date.

**Comment by schmoomsm** [comment]
> Cache is 24 hours. So it will eventually be refetching and up to date.

Excellent. Thx.

**Comment by mauserrifle** [comment]
The dropdown selection issue is fixed :) I'm closing this issue now. If you have more questions don't hesitate to ask! You helped improve the tool :+1:
