### ISSUE TITLE
user_id

### ISSUE THREAD

**Issue by hamzalija** [mauserrifle/simresults#70]
first off, thanks for sharing this tool.. I have been trying to pull out the steam ID off the log in ACC, but it seems to return empty string..
is this normal?

**Comment by mauserrifle** [comment]
Hi Hamzalija. Glad you like the tool!  I was not aware there are IDs in the ACC logs. But I see now there's a playerId. I'll make it a todo. I might be able to work on it today, else it's next week.

**Comment by hamzalija** [comment]
sweet thanks a ton. I think there is something with is wet session as well (or I might be using it wrong)

**Comment by mauserrifle** [comment]
I will look into it. Maybe the logs are richer in data now. If you could email a very recent log that would be great too.
Unfortunately I wasn't able to work on this today, the work I had planned for the website took more time than expected. Hopefully next week Tuesday.

**Comment by hamzalija** [comment]
shooting you a mail within few min.

**Comment by mauserrifle** [comment]
Thanks! 

* I added `playerId` and `serverName` parsing.
* The wet session info is currently under `Session::getOtherSettings()`.
* Unfortunately there is no date in the log files

Please update the library and let me know if there's anything :)

**Comment by hamzalija** [comment]
thank you a ton.. servername and player id is confirmed working... <3 from me
