### ISSUE TITLE
No Sector Times for RaceRoom

### ISSUE THREAD

**Issue by simracing** [mauserrifle/simresults#72]
The RaceRoomServer data reader does not pick up the lap sector times.

**Comment by mauserrifle** [comment]
Thanks for reporting! I was not aware sector times were in the logs by now. I added support for it.

**Comment by simracing** [comment]
Thank you for the quick fix!!   You are awesome and we love you at [SRO](https://simracingonline.co.uk)

**Comment by mauserrifle** [comment]
Doing it for the love :smiley:  Thanks for letting me know. I am glad you appreciate my work and are loving it! Happy simracing!
