### ISSUE TITLE
RaceRoom including DNF lap in counter

### ISSUE THREAD

**Issue by simracing** [mauserrifle/simresults#74]
Hi Maurice,
Not sure if this is really an issue or not but thought I would report it.   We had a driver who ran out of fuel on lap 13 of 13.  So he only completed 12 laps.   The results is showing him completing 13 laps.   I have included a screen shot of the result file for this guy.  It is recording 13 laps but also records a finished status of DNF.  So we were thinking the last lap should not be counted as a completed lap.   Thanks again for your awesome work!

First screen shows the Simresults page.  Second screen shows results raw data.   Lap detail collapsed for brevity.  

![image](https://user-images.githubusercontent.com/52586091/101283160-655ebc80-379e-11eb-9872-f191d18c4d9e.png)

![image](https://user-images.githubusercontent.com/52586091/101283151-5ed04500-379e-11eb-82b6-b496694920f2.png)

**Comment by mauserrifle** [comment]
Could you also mail the full log to me? This way I can analyze it better and maybe find a clever solution. I am hoping there is a missing sector time for the last lap. This would be a good detection for ignoring the lap without breaking any future log updates of the game (if they decide to fix this).

**Comment by simracing** [comment]
File is attached.   Thanks.
[R3E Vesta Portimao Test 202012040848.zip](https://github.com/mauserrifle/simresults/files/5661359/R3E.Vesta.Portimao.Test.202012040848.zip)

**Comment by mauserrifle** [comment]
Ok I fixed this. The last lap is removed in this situation:

* The driver is registered as DNF
* It is a race session
* The last lap has recorded incidents (with or without an other car)

This way the chance is smaller in the future we remove laps that might already been removed by RaceRoom.
Still very strange the driver has 3 sector times as if it was still proceeding. Buggy log.

Thanks for the input! Let me know if this works for you! 

6aa746e67e5ad2f0cefde4b534fffe4498a4e572
