### ISSUE TITLE
API config question

### ISSUE THREAD

**Issue by cheesegrits** [mauserrifle/simresults#78]
Hi,

Quick question about the API.  Which I could figure out by just testing it, but might be useful for others to see the answer here.

Is it possible to have both a global and per result group config, with the latter overriding the former?  So fill in all the main details in a global config, then just add the 'event' and 'event_link' fields in a config on each result?

Or should I just add a full config for each result and not add a global config, to get the event details added?

Thanks for a great library and web site.

**Comment by mauserrifle** [comment]
The configs are not merged but the overriding(merge) of the global config per result group sounds like a good feature. It makes the json much cleaner. I'll consider creating this. For now use config per result group, thus no global. Glad you like the tool!

**Comment by cheesegrits** [comment]
Thanks for the quick response.

I'm having an issue trying to submit through the /remote?results= API.  I get "400
The external results file can't be read".

Rather than start another issue, figured I'd just reply here - if you'd rather I open a new issue, just let me know.

The URL I'm submitting is this:

https://acrlonline.org/index.php?option=com_fabrik&format=raw&task=plugin.userAjax&method=getSimResultsEvent&eventId=102&version=1

... which is a script that produces the following JSON.  I've tried returning it both as simple inline JSON, and as a file with 'content-type: application/json'.

Any idea where I'm going wrong?

```
{
  "name": "ACRL - ACC Season 3 - Nurbugrging",
  "results": [
    {
      "name": "Split 2",
      "log": "https://acrlonline.org/index.php?option=com_fabrik&format=raw&task=plugin.userAjax&method=getResultFile&eventId=102&split=2"
    },
    {
      "name": "Split 1",
      "log": "https://acrlonline.org/index.php?option=com_fabrik&format=raw&task=plugin.userAjax&method=getResultFile&eventId=102&split=1"
    }
  ],
  "config": {
    "logo": "https://acrlonline.org/templates/g5_helium/custom/images/acrlrlogo.png",
    "logo_link": "https://acrlonline.org",
    "league": "ACRL",
    "league_link": "https://acrlonline.org",
    "event": "Nurbugrging",
    "event_link": "https://acrlonline.org/index.php/events/championships/details/19/102",
    "hide_sessions": "",
    "q_points": "",
    "points": "",
    "best_lap_points": "",
    "led_most_points": "",
    "laps_points_number": "",
    "laps_points": "",
    "stopgo_lose_points": "",
    "drivethrough_lose_points": "",
    "dnf_lose_points": "",
    "dq_lose_points": "",
    "dnf_no_points": "1",
    "dnf_ignore_losing_points": "",
    "no_indexing": "0",
    "shorten_lastnames": "0",
    "shorten_firstnames": "0",
    "team": "0",
    "hide_aids": "0"
  }
}
```

Thanks in advance for any help,

   -- hugh

**Comment by mauserrifle** [comment]
Hi Hugh,

Your url needs to be urlencoded so it becomes:

```
https%3A%2F%2Facrlonline.org%2Findex.php%3Foption%3Dcom_fabrik%26format%3Draw%26task%3Dplugin.userAjax%26method%3DgetSimResultsEvent%26eventId%3D102%26version%3D1
```

Use the urlencode method in your programming language.

But this wasn't all. The remote results api didn't process query params in remote urls. This is now fixed too :)

It works now:
https://simresults.net/remote?results=https%3A%2F%2Facrlonline.org%2Findex.php%3Foption%3Dcom_fabrik%26format%3Draw%26task%3Dplugin.userAjax%26method%3DgetSimResultsEvent%26eventId%3D102%26version%3D1

Thanks for reporting this! I will document it in the API page later.

**Comment by mauserrifle** [comment]
The merging of configs also works now! See the api page for an example.

Cheers!

**Comment by cheesegrits** [comment]
Ah!  I had tried urlencode()'ing the results= string, but that didn't seem to work anyway.  But an issue with query string params would explain that.

Thanks for the rapid response!

   -- hugh
