### ISSUE TITLE
Allow ACC result json files to be read by the remote api

### ISSUE THREAD

**Issue by stewieoO** [mauserrifle/simresults#79]
Game: ACC

Currently the [https://simresults.net/api](https://simresults.net/api) only supports reading from the server log files, while the manual  upload supports the result json files.

So either the api is not documented fully or that feature is missing.

Is it possible to allow the usage of the result json files in the api?

**Comment by stewieoO** [comment]
Nervermind. I just found what i was looking for.
I saw that json files work in #78 and then noticed i was missing a `"` in my config file.

**Comment by mauserrifle** [comment]
:+1:  

I will see also that the docs are more clear. `.txt` examples might be confusing regarding what is supported. Same files you manually upload will work through the API. It's not a difference.
